### ISSUE TITLE
Phaser, Flanger, Chorus

### ISSUE THREAD

**Issue by codechaosasd** [ifsm/pymus#15]
**Is your feature request related to a problem? Please describe.**
Not exactly, but it's important for musicologists to use theese effects in own programming.

**Describe the solution you'd like**
I can prepare a jupyter notebook with theese audio effects implemented as code.

**Comment by TimZiemer** [comment]
Great features indeed. I've created a new branch for you. You may also help @jonathanpostawka get his all pass filter to work, as you will need all pass filters for the phaser.
